#! /bin/sh

##############################################
# _                                          
#| |__  ___ _ ____      ___ __ ___  _ __ ___ 
#| '_ \/ __| '_ \ \ /\ / / '_ ` _ \| '__/ __|
#| |_) \__ \ |_) \ V  V /| | | | | | | | (__ 
#|_.__/|___/ .__/ \_/\_/ |_| |_| |_|_|  \___|
#          |_|                               
##############################################

zsh ~/.config/bspwm/killscript &
sxhkd &

###Config

#bspc monitor eDP -d 1 2 3 4 5 6 7 8 9 10
bspc monitor eDP -d          

bspc config border_width         2
#bspc config border_radius       10
bspc config top_padding         24
bspc config right_padding       -4
bspc config left_padding        -4
bspc config bottom_padding      -4
bspc config window_gap          16
bspc config top_monocle_padding  0
bspc config right_monocle_padding 0
bspc config left_monocle_padding 0
bspc config bottom_monocle_padding 0

. "${HOME}/.cache/wal/colors.sh"
bspc config focused_border_color "$color6"
bspc config presel_feedback_color "$color6"
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_pointer true

###Rules
bspc rule -a "Zathura"	state=tiled
bspc rule -a URxvt:cmatrixterm state=fullscreen
bspc rule -a URxvt:dropdown state=floating

###Application startup
wal -R -n -q
zsh ~/.config/polybar/launch.sh &
picom --experimental-backends --config ~/.config/bspwm/picom.conf &
/usr/lib/geoclue-2.0/demos/agent &
#/usr/lib/policykit-1-pantheon/io.elementary.desktop.agent-polkit &
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &
start-pulseaudio-x11 &
~/.fehbg &
redshift &
dunst &
unclutter &
desknamer &
#btops &
xset s 420 179
xss-lock -n ~/.config/bspwm/.screensaver -l -- ~/.config/bspwm/mantablockscreen.in &
#xss-lock -- ~/.config/bspwm/mantablockscreen.in &
zsh ~/.config/bspwm/localserver &
udiskie &
xset r rate 440 50
xwinwrap -g 200x200+583+283 -fdt -o 0.7 -sh circle -d -- gifview -w WID ~/.config/bspwm/quarksmall.gif -a

