#!/bin/sh
color="#537E9D'>"
col="<span color='"
end="</span>"
FULL="•"
EMPTY="○"
value="${2:-10}"

case $1 in
up)
	light -A "$value"
	label=""
	;;
down)
	light -U "$value"
	label=""
	;;
esac

brightness="$(light -G)"
#brightnessLevel=$(cat /sys/class/backlight/intel_backlight/actual_brightness)
#maxBrightness=$(cat /sys/class/backlight/intel_backlight/max_brightness)
#brightness=$(echo "scale=2; ($brightnessLevel/$maxBrightness)*100" | bc)
brightness=${brightness%.*}
barFull=$(seq -s "$FULL" $((brightness / 5)) | sed 's/[0-9]//g')
barEmpty=$(seq -s "$EMPTY" $((20 - brightness / 5)) | sed 's/[0-9]//g')
dunstify -t 1000 -r 2593 -u normal "$label Brightness: $brightness%" "$col$color$barFull$end$barEmpty"

